# Generated by Django 4.1.7 on 2023-04-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola_mundo', '0003_producto_venta_delete_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_Producto',
            field=models.IntegerField(),
        ),
    ]
